/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:88f54eb6-e331-4e8e-99fc-4c92d634b120",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8OX7PiPFG",
    "aws_user_pools_web_client_id": "6ipoev7v9tlaiuft26co9ps84f",
    "oauth": {}
};


export default awsmobile;
